name: 🐛 Report Issue
description: Report a bug or problem
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Explain the issue clearly
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Step-by-step to reproduce the issue
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior

  - type: input
    attributes:
      label: Environment (Device, Browser, etc)
